version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        environment:
            NOTIFICATION_MAIL: 'erley9@hotmail.com'
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel
            
    front:
        container_name: frontend
        image: node:lts
        working_dir: /var/www/html/app/
        entrypoint: /bin/bash
        ports:
            - "9200:9200"
        volumes:
        - ./front/:/var/www/html/app
        tty: true
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
